---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress02
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress02
  template:
    metadata:
      labels:
        app: wordpress02
    spec:
      containers:
        - name: wordpress02
          image: wordpress:5.4-php7.1-apache
          ports:
          - containerPort: 80
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: wordpress
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-volume02
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-balancer02
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress02


