apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-word01
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.37.105
    path: "/mnt/IT-Academy/nfs-data/sa2-16-21/amurygin/word01"
