apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volume02
  namespace: project
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: "nfs-word02"
  storageClassName: ""


